name: Bot

on:
  workflow_call:

permissions:
  contents: write

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
      with:
        python-version: "3.9"

    - name: Set up git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Create README.md
      run: python ./create-readme.py

    - name: Commit and push
      continue-on-error: true
      run: |
        git commit -am "Update README.md"
        git push origin "${{ github.ref_name }}"

  tag:
    runs-on: ubuntu-latest
    needs: readme

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: 'main'

    - id: get_version
      name: Get version
      run: |
        ver_toml=$(grep "version = " pyproject.toml | cut -d\" -f2)
        echo "version=$ver_toml" >> "$GITHUB_OUTPUT"

    - name: Tag version
      run: |
        git tag "${{ steps.get_version.outputs.version }}"
        git push origin "${{ steps.get_version.outputs.version }}"
