name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'pyproject.toml'

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  bot:
    needs: ci
    permissions:
      contents: write
    uses: ./.github/workflows/bot.yml
